version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chess-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18o1gtwpdipw5"
s3_prefix = "chess-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=063772529573.dkr.ecr.us-east-1.amazonaws.com/demo-app-chess"]
